version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: petclinic-postgres
    restart: always
    environment:
      POSTGRES_DB: petclinic
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  petclinic:
    image: talgatdilmurat/spring-petclinic
    container_name: petclinic-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8888:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petclinic
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: postgres

volumes:
  pgdata:
